// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.DataAccess.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Entities.Guild", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Disabled");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Guilds");

                    b.HasData(
                        new
                        {
                            Id = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 50, DateTimeKind.Utc).AddTicks(103),
                            Disabled = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 50, DateTimeKind.Utc).AddTicks(104),
                            Name = "NERV"
                        },
                        new
                        {
                            Id = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 68, DateTimeKind.Utc).AddTicks(5349),
                            Disabled = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 68, DateTimeKind.Utc).AddTicks(5350),
                            Name = "WILE: EVA Pilots"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Invite", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Disabled");

                    b.Property<string>("GuildId")
                        .IsRequired();

                    b.Property<string>("MemberId")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Status");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("MemberId");

                    b.ToTable("Invites");

                    b.HasData(
                        new
                        {
                            Id = "89dd1816-dd87-4e8e-97f5-fc5b32f900bd",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 77, DateTimeKind.Utc).AddTicks(9681),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 77, DateTimeKind.Utc).AddTicks(9682),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "8cac0c89-b5b4-4b1a-8395-525395ba3d3b",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(3843),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "3cb0ba50-03d9-48db-93ca-692cb9d68131",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(3844),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "bedfa422-317d-4640-a4c7-84f47e2fcd6d",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4151),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "18234e65-8cb1-42e8-9cf4-e4d37980752a",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4151),
                            Status = (short)3
                        },
                        new
                        {
                            Id = "700dad75-3364-4d75-ab44-cec40dcfdeca",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4290),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "bf449ca7-5183-46ad-a2eb-edf804e20a0e",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4290),
                            Status = (short)4
                        },
                        new
                        {
                            Id = "c06ed199-312c-42f0-a582-b471129e41af",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4372),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4372),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "ae609940-4505-4977-813d-d26428672315",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4455),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "bf449ca7-5183-46ad-a2eb-edf804e20a0e",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4456),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "b2b4625b-d424-4d8e-aee7-19efa63eb062",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4548),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "18234e65-8cb1-42e8-9cf4-e4d37980752a",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4548),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "684737ff-ab4b-4b68-b7f1-a8739e0b1840",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4624),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "e3f46444-78f3-4b94-b703-bc056121fc16",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4624),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "ab532a05-606d-4931-b81b-8ce522dd4496",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4697),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "84a7896c-264e-44de-9d36-e2edc3d201e7",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4698),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "1d350c02-d364-41cf-b38c-fa2c242af4c6",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4773),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4773),
                            Status = (short)2
                        },
                        new
                        {
                            Id = "f0dc8d5a-89eb-4496-a14c-bd041b36448f",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4884),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "9fad438a-3555-4583-9621-2c065ad93084",
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 80, DateTimeKind.Utc).AddTicks(4884),
                            Status = (short)2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Disabled");

                    b.Property<string>("GuildId");

                    b.Property<bool>("IsGuildMaster");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = "bf449ca7-5183-46ad-a2eb-edf804e20a0e",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 71, DateTimeKind.Utc).AddTicks(7729),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            IsGuildMaster = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 71, DateTimeKind.Utc).AddTicks(7731),
                            Name = "Mari Makinami, EVA 05 Pilot"
                        },
                        new
                        {
                            Id = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(7715),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            IsGuildMaster = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(7716),
                            Name = "Asuka Langley Sohryu, EVA 02 Pilot"
                        },
                        new
                        {
                            Id = "3cb0ba50-03d9-48db-93ca-692cb9d68131",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(7977),
                            Disabled = false,
                            IsGuildMaster = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(7977),
                            Name = "Rei Ayanami, EVA 00 Pilot"
                        },
                        new
                        {
                            Id = "18234e65-8cb1-42e8-9cf4-e4d37980752a",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8045),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            IsGuildMaster = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8046),
                            Name = "Shinji Ikari, EVA 01 Pilot"
                        },
                        new
                        {
                            Id = "e3f46444-78f3-4b94-b703-bc056121fc16",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8122),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            IsGuildMaster = true,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8123),
                            Name = "Gendo Ikari, NERV Comander"
                        },
                        new
                        {
                            Id = "84a7896c-264e-44de-9d36-e2edc3d201e7",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8314),
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            IsGuildMaster = false,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8315),
                            Name = "Kozo Fuyutsuk, NERV Deputy Comander"
                        },
                        new
                        {
                            Id = "9fad438a-3555-4583-9621-2c065ad93084",
                            CreatedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8403),
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            IsGuildMaster = true,
                            ModifiedDate = new DateTime(2020, 3, 26, 16, 24, 52, 75, DateTimeKind.Utc).AddTicks(8403),
                            Name = "Misato Katsuragi, WILE Comander"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Membership", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Disabled");

                    b.Property<string>("GuildId")
                        .IsRequired();

                    b.Property<string>("MemberId")
                        .IsRequired();

                    b.Property<DateTime>("Since")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Until")
                        .ValueGeneratedOnUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("MemberId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = "63c3c07a-7d10-4585-879e-60ff90f30cfa",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            Since = new DateTime(2020, 3, 17, 19, 18, 42, 619, DateTimeKind.Unspecified).AddTicks(29),
                            Until = new DateTime(2020, 3, 17, 21, 24, 25, 62, DateTimeKind.Unspecified).AddTicks(6216)
                        },
                        new
                        {
                            Id = "785e1d4f-99dd-4152-ade0-bce244c0eec1",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "bf449ca7-5183-46ad-a2eb-edf804e20a0e",
                            Since = new DateTime(2020, 3, 17, 19, 20, 47, 23, DateTimeKind.Unspecified).AddTicks(5603),
                            Until = new DateTime(2020, 3, 17, 19, 54, 32, 580, DateTimeKind.Unspecified).AddTicks(284)
                        },
                        new
                        {
                            Id = "048fca04-54c9-41fd-af36-a56e01426159",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            Since = new DateTime(2020, 3, 17, 23, 9, 49, 47, DateTimeKind.Unspecified).AddTicks(6435),
                            Until = new DateTime(2020, 3, 17, 23, 10, 59, 525, DateTimeKind.Unspecified).AddTicks(1100)
                        },
                        new
                        {
                            Id = "ef2fbc73-2d66-4f81-bb42-1e5dad58c276",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            Since = new DateTime(2020, 3, 18, 0, 4, 35, 630, DateTimeKind.Unspecified).AddTicks(3147),
                            Until = new DateTime(2020, 3, 18, 0, 22, 31, 664, DateTimeKind.Unspecified).AddTicks(5485)
                        },
                        new
                        {
                            Id = "8907eb3f-b192-42f1-9fe7-a91c4dd799e0",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "3cb0ba50-03d9-48db-93ca-692cb9d68131",
                            Since = new DateTime(2020, 3, 18, 0, 14, 49, 870, DateTimeKind.Unspecified).AddTicks(9813),
                            Until = new DateTime(2020, 3, 18, 15, 25, 21, 374, DateTimeKind.Unspecified).AddTicks(2161)
                        },
                        new
                        {
                            Id = "c9aa80ec-229f-4763-ac30-0b1584ac2943",
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            Since = new DateTime(2020, 3, 18, 0, 22, 31, 665, DateTimeKind.Unspecified).AddTicks(6800),
                            Until = new DateTime(2020, 3, 18, 15, 17, 3, 492, DateTimeKind.Unspecified).AddTicks(4124)
                        },
                        new
                        {
                            Id = "d1307584-b524-48e2-91fa-1882c9819ac8",
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "bf449ca7-5183-46ad-a2eb-edf804e20a0e",
                            Since = new DateTime(2020, 3, 18, 1, 3, 38, 622, DateTimeKind.Unspecified).AddTicks(9484)
                        },
                        new
                        {
                            Id = "970a0fea-aa33-4898-932b-e713045c9fce",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "18234e65-8cb1-42e8-9cf4-e4d37980752a",
                            Since = new DateTime(2020, 3, 18, 2, 38, 44, 175, DateTimeKind.Unspecified).AddTicks(8894)
                        },
                        new
                        {
                            Id = "63b7cac2-07b5-4bf1-a3ae-90e4b2f65c2e",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "e3f46444-78f3-4b94-b703-bc056121fc16",
                            Since = new DateTime(2020, 3, 18, 7, 20, 19, 667, DateTimeKind.Unspecified).AddTicks(5361)
                        },
                        new
                        {
                            Id = "408b0fcf-7a0e-46d3-aa2a-8cc41bd8c492",
                            Disabled = false,
                            GuildId = "96685bc4-dcb7-4b22-90cc-ca83baff8186",
                            MemberId = "84a7896c-264e-44de-9d36-e2edc3d201e7",
                            Since = new DateTime(2020, 3, 18, 15, 4, 32, 920, DateTimeKind.Unspecified).AddTicks(9975)
                        },
                        new
                        {
                            Id = "39823673-5f77-4b54-9f2b-ea2818d9c490",
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "5cd3f816-6b0f-4ba6-aeb5-26d70281f7e1",
                            Since = new DateTime(2020, 3, 18, 15, 27, 11, 115, DateTimeKind.Unspecified).AddTicks(8971)
                        },
                        new
                        {
                            Id = "016a61d1-dd66-47fe-8404-195ce90be07f",
                            Disabled = false,
                            GuildId = "0bf46ff3-42a8-4dbb-a037-009d831b3263",
                            MemberId = "9fad438a-3555-4583-9621-2c065ad93084",
                            Since = new DateTime(2020, 3, 18, 15, 28, 14, 381, DateTimeKind.Unspecified).AddTicks(5450)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Invite", b =>
                {
                    b.HasOne("Domain.Entities.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Membership", b =>
                {
                    b.HasOne("Domain.Entities.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
